#!/usr/bin/env python3
"""Generate shortlist/trait-evidence.js from docs/trait-picker-classification.md.

The classification doc is the reviewed source of truth for which bullet
supports which trait (and which bullets support none). This script turns its
per-vehicle tables into the static evidence module the Shortlist's trait
picker shows under each trait row, so the two can never be edited apart:
change the classification, rerun this, commit both.

Output shape:
  TRAIT_EVIDENCE: { <field_id>: [ { v: vehicle_id, text, polarity } ] }
  GENERAL_EVIDENCE: [ { v, text, polarity } ]   # bullets tied to no trait

Evidence is keyed by *field* rather than picker-row id because several rows
share a field (both overnight_climate rows, both tow_class rows, ...): the
same supporting bullets apply to each.

Usage: python3 scripts/gen_trait_evidence.py   (from anywhere; paths are repo-relative)
"""
import json
import re
import os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOC = os.path.join(REPO, "docs", "trait-picker-classification.md")
OUT = os.path.join(REPO, "shortlist", "trait-evidence.js")

# Field tokens the traits column may name, in the order the picker groups them.
# "ground_clearance_in" rows feed the clearance_class trait.
FIELD_TOKENS = {
    "overnight_climate": "overnight_climate",
    "sliding_doors": "sliding_doors",
    "stealth_profile": "stealth_profile",
    "camper_popularity_tier": "camper_popularity_tier",
    "sleeps_six_feet": "sleeps_six_feet",
    "tow_class": "tow_class",
    "clearance_class": "clearance_class",
    "ground_clearance_in": "clearance_class",
    "rear_seat_fold": "rear_seat_fold",
    "drivetrain_bucket": "drivetrain_bucket",
    "onboard_ac_power": "onboard_ac_power",
    "spare_tire": "spare_tire",
    "still_in_production": "still_in_production",
    "dc_fast_charging": "dc_fast_charging",
    "roof_rails": "roof_rails",
}

HEADING = re.compile(r"^### (\S+) \(")
ROW = re.compile(r"^\| (pro|con) \| (.*) \| (D|R|D\+R|E) \| (.*) \|$")


def main():
    evidence = {}
    general = []
    vehicle = None
    rows = 0
    with open(DOC, encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            m = HEADING.match(line)
            if m:
                vehicle = m.group(1)
                continue
            m = ROW.match(line)
            if not m or vehicle is None:
                continue
            rows += 1
            side, text, bucket, traits_cell = m.groups()
            entry = {
                "v": vehicle,
                "text": text.replace("\\|", "|"),
                "polarity": side,
            }
            fields = []
            for token, field in FIELD_TOKENS.items():
                if re.search(rf"\b{token}\b", traits_cell) and field not in fields:
                    fields.append(field)
            if fields:
                for field in fields:
                    evidence.setdefault(field, []).append(entry)
            else:
                # Includes both pure-editorial rows ("— (...)") and rows whose
                # only mapped fields are numeric spec restatements (mpg, price,
                # cargo volume...) with no picker row. Only the former belong in
                # the general list: a bullet that restates a table column is
                # already visible as that column.
                if traits_cell.startswith("—"):
                    general.append(entry)
    assert rows == 250, f"expected 250 classification rows, parsed {rows}"

    body = (
        "// Generated by scripts/gen_trait_evidence.py from\n"
        "// docs/trait-picker-classification.md — do not edit by hand. Rerun the\n"
        "// script after changing camper_pros/camper_cons or the classification.\n"
        f"export const TRAIT_EVIDENCE = {json.dumps(evidence, indent=1, ensure_ascii=False)};\n\n"
        f"export const GENERAL_EVIDENCE = {json.dumps(general, indent=1, ensure_ascii=False)};\n"
    )
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(body)
    mapped = sum(len(v) for v in evidence.values())
    print(f"wrote {os.path.relpath(OUT, REPO)}: {mapped} field-mapped entries "
          f"across {len(evidence)} fields, {len(general)} general entries")


if __name__ == "__main__":
    main()
